### ISSUE TITLE
Emoji mentions force newline in preview

### ISSUE THREAD

**Issue by yamikuronue** [apxltd/what-bugs#70] opened 2016-03-30 16:35 UTC
You can't do a mention-emoji (like :yamikuronue:) inline. It forces a line break.

**Comment by BenLubar** [comment] 2016-03-30 18:09
Can't reproduce here: https://what.thedailywtf.com/topic/19544/emoji-mentions

![screenshot 2016-03-30 at 13 08 35](https://cloud.githubusercontent.com/assets/4257305/14152371/90939b26-f678-11e5-8f91-ed03f9a4a660.png)

**Comment by yamikuronue** [comment] 2016-03-30 18:14
It's a preview glitch. It's right when it posts, but the preview lies, so in all my posts I've been fixing it anyway.

**Comment by BenLubar** [comment] 2016-03-30 18:26
fixed by overriding the skin CSS

**Closed as completed by BenLubar** 2016-03-30 18:26 UTC
