### ISSUE TITLE
Teaser doesn't show quoted text

### ISSUE THREAD

**Issue by coldandtired** [apxltd/what-bugs#28] opened 2016-03-22 22:18 UTC
The teaser box puts a quote's author but not the quote itself, instead making it look like the first line of the post is the quote, which could lead to much trolling.

Teaser:

![teaser](https://cloud.githubusercontent.com/assets/1159425/13969595/1f809a82-f084-11e5-97e6-95a762862ae8.png)

Real post:

![actual](https://cloud.githubusercontent.com/assets/1159425/13969598/2136fac4-f084-11e5-8a1a-9877bf1cfb9a.png)

**Comment by loopback0** [comment] 2016-03-22 23:01
;)
https://github.com/apapadimoulis/what-bugs/issues/20

**Comment by BenLubar** [comment] 2016-03-23 00:39
Duplicate of #20

**Closed as completed by BenLubar** 2016-03-23 00:39 UTC
Labels: duplicate
