### ISSUE TITLE
Search entirely incompetent

### ISSUE THREAD

**Issue by blakeyrat-dailywtf** [apxltd/what-bugs#55] opened 2016-03-25 17:43 UTC
Steps to reproduce:

1) Find the title of a thread, copy it into your clipboard; I used "Blakeyrat's Videos Thread (Robots in the News et al.)"
2) Click the magnifying glass to search the forums
3) Paste-in the thread title you had copied previously

Expected result:

NodeBB brings up the thread in milliseconds, and the thread you're searching for is top of the results

Actual result:

After about 45 seconds of chugging, the thread you searched for not at the top of the results, despite you quoting its title exactly:

![image](https://cloud.githubusercontent.com/assets/18073711/14050040/58b4cfbe-f276-11e5-8ce1-3b6da83fb582.png)

**Comment by blakeyrat-dailywtf** [comment] 2016-03-25 17:44
Note that screenshot isn't corrupted; that's the exact screen I got. Even the giant YouTube play button and weird markup hovering over post content.

**Comment by yamikuronue** [comment] 2016-03-25 18:12
Duplicate of #8, which is closed, but is obviously not fixed

**Comment by blakeyrat-dailywtf** [comment] 2016-03-25 18:14
Ben L, when you get a job in the workplace you can't just close bugs without letting the person who reported it (or your QA department, if you have one) re-test. The best you as a developer can do is mark it as "I think I resolved this", whatever word might be used for that state on GitHub.

**Comment by BenLubar** [comment] 2016-03-25 18:14
re-opening #8. I thought that was fixed by the results being sorted, but apparently not.

**Closed as completed by BenLubar** 2016-03-25 18:14 UTC
Labels: duplicate
