### ISSUE TITLE
No, I wasn't mentioned, my group was...

### ISSUE THREAD

**Issue by pauljherring** [apxltd/what-bugs#143] opened 2016-06-20 18:45 UTC
![screenshot from 2016-06-20 19-42-46](https://cloud.githubusercontent.com/assets/3939886/16206221/40733934-371f-11e6-8c83-1d30a456afab.png)

Could we have some clarity on notifications as to whether it was a mention as an individual or as part of a group (in this particular instance @mods)

**Comment by BenLubar** [comment] 2016-06-20 18:46
Duplicate of julianlam/nodebb-plugin-mentions#76

**Closed as completed by BenLubar** 2016-06-20 18:46 UTC
Labels: duplicate, sent upstream
