### ISSUE TITLE
Two bug report banners

### ISSUE THREAD

**Issue by marczellm** [apxltd/what-bugs#135] opened 2016-05-31 12:27 UTC
![wtdwtf bug](https://cloud.githubusercontent.com/assets/6771275/15674201/cb688d6c-273b-11e6-9845-7dc069aae9c5.PNG)

**Comment by BenLubar** [comment] 2016-05-31 15:20
7th duplicate of NodeBB/nodebb-theme-persona#281

😜

**Closed as completed by BenLubar** 2016-05-31 15:20 UTC
Labels: duplicate
