### ISSUE TITLE
Read notifications' text is unreadable under darkly

### ISSUE THREAD

**Issue by whjms** [apxltd/what-bugs#142] opened 2016-06-16 17:03 UTC
Looks like the notification text colour is black:
![capture](https://cloud.githubusercontent.com/assets/3392687/16125684/b3641720-33c2-11e6-9737-ead4e5a2b6c0.PNG)

I'm not using any Stylish theme.

**Comment by BenLubar** [comment] 2016-06-16 17:11
Duplicate of https://github.com/NodeBB/NodeBB/issues/4735#issuecomment-225926265

**Closed as completed by BenLubar** 2016-06-16 17:11 UTC
Labels: duplicate, sent upstream
